---
- name: "copy files to Host"
  hosts: Hosts
  tasks:
  - name: Copying files to Host
    become: True
    become_user: root                                                                                                       
    copy:
      src: /Users/kaufmann/Documents/Ansible/image-tester-ansible/Playbooks/send_file/scripts/ubuntu_debian/
      dest: "/home/{{ ansible_user }}/scripts/"
      owner: root
      mode: 0755
    with_fileglob:
      - /Users/kaufmann/Documents/Ansible/image-tester-ansible/Playbooks/send_file/scripts/ubuntu_debian/*
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: "copy files to Host"
  hosts: Hosts
  tasks:
  - name: Copying files to Host
    become: True
    become_user: root                                                                                                       
    copy:
      src: /Users/kaufmann/Documents/Ansible/image-tester-ansible/Playbooks/send_file/scripts/fedora_centos/
      dest: "/home/{{ ansible_user }}/scripts/"
      owner: root
      mode: 0755
    with_fileglob:
      - /Users/kaufmann/Documents/Ansible/image-tester-ansible/Playbooks/send_file/scripts/fedora_centos/*
    when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS'